### ISSUE TITLE
[BUG]: gvcf2hvcf  arguments not working

### ISSUE THREAD

**Issue by em255** [maize-genetics/phg_v2#128]
### Description

# Hvcf from PHG created Gvcf
phg gvcf2hvcf \
    --db-path /path/to/dbs \
    --bed /path/to/bed_file.bed \
    --reference-file /my/ref.fasta \
    --gvcf-dir /my/gvcf/files \
    -o /path/to/hvcf
    
   This is the template command however this command cannot accept a -o option.  

### Expected behavior

The error messages are going great so far!  I'm testing this out without hand holding so hopefully can help with some of the usability.

**Comment by lynnjo** [comment]
Thanks for your feedback.  The documentation is incorrect - I will update it.  The h.vcf files are written to the folder indicated by the gvcf-dir parameter (ie, they are written to the same folder than contains the gvcf files).
