### ISSUE TITLE
[BUG]: kmer index is empty

### ISSUE THREAD

**Issue by em255** [maize-genetics/phg_v2#136]
### Description

I completed running the export-vcf command and got a HVCF folder full of gvcfs filled with hashed alternate alleles that look like haplotype IDs.  However when I get to the kmer index command I get an empty kmer index.  

[main] INFO net.maizegenetics.phgv2.pathing.BuildKmerIndex 2024-04-02 21:06:13,441: HaplotypeGraph built in 75.99819 ms.
[main] DEBUG net.maizegenetics.phgv2.pathing.BuildKmerIndex 2024-04-02 21:06:13,464: Finished building kmer keep set, keep set size = 0, discard set size = 0, elapse time 2.65E-5 sec
[main] INFO net.maizegenetics.phgv2.pathing.BuildKmerIndex 2024-04-02 21:06:13,472: Saved kmer mapping to CassavaPHG/HVCF/kmerIndex.txt, elapsed time 0.001252576 sec

### Expected behavior

Should be a complete kmer index for alignment

### PHG version

2.2.66.115

**Comment by em255** [comment]
The issue must be due to `keep set size = 0`, but don't know how to address that

**Comment by zrm22** [comment]
It looks like the graph is being built without sequence.  Can you post the command you use and the full log.  @pjbradbury should be able to take a look sometime next week.

**Comment by em255** [comment]
`./phg build-kmer-index --hvcf-dir CassavaPHG/HVCF --db-path CassavaPHG/`

Here is what the HVCF folder looks like:
![Screenshot 2024-04-08 114240](https://github.com/maize-genetics/phg_v2/assets/84086921/18bc607b-a337-4a77-91c8-b001f417c4e6)

These vcfs were produced from previous command in documentation:
`./phg export-vcf --dataset-type hvcf --outputDir CassavaPHG/HVCF --db-path CassavaPHG/ --sample-names Col1010Bhap1,Col1010Bhap2,Col1484hap1,Col1484hap2,Col1678hap1,Col1678hap2,Col282hap1,Col282hap2,Col386hap1,Col386hap2,Col517hap1,Col517hap2,Col856hap1,Col856hap2,Col875hap1,Col875hap2`

These vcfs look good to me with alternate alleles being hash codes for haplotypes and the # sites being the # of refranges.

**Comment by pjbradbury** [comment]
The problem is that BuildKmerIndex is expecting the hvcf files to have a .h.vcf extension, not just .vcf. The simplest thing would be just to change the file extensions then re-run BuildKmerIndex. That is something we need to fix programmatically, but in the meantime changing the file extensions yourself should work.

**Comment by em255** [comment]
Thanks Peter, seems to be building now!
