### ISSUE TITLE
[BUG]: There is no command in phg prepare-slurm-align-file

### ISSUE THREAD

**Issue by sidevshiy** [maize-genetics/phg_v2#183]
### Description

Hello,
I used preparation script from SLURM usage docs but it seems like there is no command "prepare-slurm-align-file".

Usage: phg [<options>] <command> [<args>]...

Options:
  --version   Show the version and exit
  -h, --help  Show this message and exit

Commands:
  setup-environment          Create a conda environment for PHG
  initdb                     Create TileDB datasets for g.vcf and h.vcf files
  create-ranges              Create a BED file of reference ranges from a GFF file
  prepare-assemblies         Annotate FASTA file Id lines with sample names, write new FASTAs with name <sampleName>.fa
  agc-compress               Create a single AGC compressed file from an input of FASTA files created with the phg
                             prepare-assemblies command
  align-assemblies           Align prepared assembly fasta files using AnchorWave.
  create-anchorwave-dotplot  create a dot plot stored in PNG file from anchowave anchorspro file
  create-ref-vcf             Create and load to tiledb a haplotype VCF for the reference genome
  create-maf-vcf             Create g.vcf and h.vcf files from AnchorWave MAF files
  gvcf2hvcf                  Create h.vcf files from existing PHG created g.vcf files
  hvcf2gvcf                  Create g.vcf file for a PHG pathing h.vcf using data from existing PHG created g.vcf files
  load-vcf                   Load g.vcf and h.vcf files into TileDB datasets
  export-vcf                 Export given samples to an h.vcf file
  build-kmer-index           Create a kmer index for a HaplotypeGraph. By default the file will be written to
                             <hvcfDir>/kmerIndex.txt
  map-kmers                  Map Kmers to the pangenome reference
  find-paths                 Impute best path(s) using read mappings.
  create-fasta-from-hvcf     Create a FASTA file from a h.vcf file or TileDB directly
  merge-hvcfs                Merge multiple HVCF files into a single HVCF file.
  merge-gvcfs                Merge GVCF files into Single VCF file
  calc-vcf-metrics           Calculate quality control metrics on g.vcf files
  start-server               Starts PHGv2 BrAPI Server

### PHG version

phg version 2.3.7.144

**Comment by lynnjo** [comment]
phg.tar file with Tag 2.3.8.145 and later has this fix.  Let me know if you still see problems - thanks.

**Comment by sidevshiy** [comment]
Thank you!
