### ISSUE TITLE
[BUG]: map-kmers does not fully strip file extension that includes .gz suffix

### ISSUE THREAD

**Issue by matthewwiese** [maize-genetics/phg_v2#205]
### Description

Hi folks. Minor UX bug. `phg map-kmers` does not fully strip a `.fastq.gz` extension as per what is written in the documentation [here](https://phg.maizegenetics.net/imputation/#optional-parameters_1)  (scroll down to the "Note" below example directory listing). My mapping keyfile entries look like this:

```
SRR11038088	data/fastq/PRJNA605407/SRR11038088_1.fastq.gz	data/fastq/PRJNA605407/SRR11038088_2.fastq.gz
```

The resulting read mapping file looks like `SRR11038088_1.fastq_readMapping.txt`. Seems like a little bit of additional logic to determine if a file is gzipped is all that's needed.

Not sure if this is addressed in the branch Zack linked me last week - if so, sorry for the unnecessary issue!

I'm loving using v2 so far, the whole experience has been smooth. Also, props on the documentation, it is a dream!

### Expected behavior

I expected the full file extension to be removed as is written in the documentation.

### PHG version

2.3.16.153

**Comment by zrm22** [comment]
Hi Matt,

No this is new, I will update after I merge in the other branch.  The other branch will bring PHGv2 up to version 2.4 and we can go from there with new updates.  I will keep you posted when this is brought in.  

Thanks for bringing it to our attention!

Zack

**Comment by zrm22** [comment]
In PR now: [here](https://github.com/maize-genetics/phg_v2/pull/206)

**Comment by zrm22** [comment]
This has been updated with the most recent version of PHGv2.4
