### ISSUE TITLE
[BUG]: phg create-maf-vcf

### ISSUE THREAD

**Issue by ClayBirkett** [maize-genetics/phg_v2#264]
### Description

INFO net.maizegenetics.phgv2.cli.CreateMafVcf 2024-12-19 00:02:06,506: CreateASMHvcfs: processing /project/genolabswheatphg/clay_ph
g/maf_files/Renan.maf
getVariantContextsfromMAF: Processing a single genome
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:467)

export JAVA_OPTS="-Xmx256g"

any idea why I am getting this error?

### PHG version

2.4.33.188

**Comment by tcasstevens** [comment]
Try
export _JAVA_OPTIONS=-Xmx256g

**Comment by ClayBirkett** [comment]
I tried using the _JAVA_OPTIONS and that made it worse. It crashed immediately with a java out of memory error. I am using openjdk version "22.0.1-internal" 2024-04-16. I'll try switching to one of the oracle java versions

**Comment by ClayBirkett** [comment]
same out of memory problem with java/17. Another idea is to remove assemblies with only scaffolds. How would I remove an assembly from the create-mat-vcf step?

**Comment by lynnjo** [comment]
@ClayBirkett Do you know which assemblies those are?  You could remove the scaffold-only assemblies from the maf-dir you give the create-maf-vcf command.  That would prevent them from being processed.  Can you tell from top or other means how much memory is being used?  Is it exceeding the 256G you gave it?  Depending on the size of the files, it may actually need more memory.  I'll look at the code to see where we're hanging onto memory.  We do pull sequence to make the hapid from the md5 hash.

How large are you chromosomes?

**Comment by lynnjo** [comment]
Also, are you able to give it more memory?  How large is the machine on which you're running?

**Comment by ClayBirkett** [comment]
I'm working on wheat. I'll try doubling the memory in my java and sbatch commands.

**Comment by ClayBirkett** [comment]
using java_options=Xmx512g solved the problem while running on a 1024g machine. I plan to add another 10-20 assemblies so I'll have to figure a way to limit memory use
